const Joi = require("joi");

exports.schema = {
	createCallSchema: Joi.object({
		client_id: Joi.number().optional(),
		// column_priority: Joi.number().optional().default(0),
		agent_id: Joi.number().optional(),
		company_name: Joi.string().max(191).optional(),
		salutation: Joi.string()
			.valid("mr", "mrs", "miss", "dr", "sir", "madam")
			.optional(),
		client_name: Joi.string().max(191).optional(),
		client_email: Joi.string().email().optional(),
		mobile: Joi.string().max(191).optional(),
		cell: Joi.string().max(191).optional(),
		country: Joi.string().max(191).optional(),
		note: Joi.string().optional(),
		next_follow_up: Joi.string().valid("yes", "no").default("yes"),
		value: Joi.number().optional().default(0),
		// added_by: Joi.number().optional(),
		// last_updated_by: Joi.number().optional(),
		// hash: Joi.string().optional(),
		product_id: Joi.number().optional(),
		lead_id: Joi.string().valid("Pending", "Converted").default("Pending"),
		// converted_by: Joi.string().optional(),
		company_id: Joi.number().optional().default(1),
		assign_by: Joi.number().optional(),
		last_assign_date: Joi.date().optional(),
		project_id: Joi.number().optional(),
		salary: Joi.number().max(6).optional(),
	}),

	updateCallSchema: Joi.object({
		client_id: Joi.number().integer().optional(),
		column_priority: Joi.number().integer().optional(),
		agent_id: Joi.number().integer().optional(),
		company_name: Joi.string().max(191).optional(),
		salutation: Joi.string()
			.valid("mr", "mrs", "miss", "dr", "sir", "madam")
			.optional(),
		client_name: Joi.string().max(191).optional(),
		client_email: Joi.string().email().optional(),
		mobile: Joi.string().max(191).optional(),
		cell: Joi.string().max(191).optional(),
		country: Joi.string().max(191).optional(),
		note: Joi.string().optional(),
		next_follow_up: Joi.string().valid("yes", "no").default("yes"),
		value: Joi.number().optional().default(0),
		added_by: Joi.number().integer().optional(),
		last_updated_by: Joi.number().integer().optional(),
		hash: Joi.string().optional(),
		product_id: Joi.number().integer().optional(),
		lead_id: Joi.string().valid("Pending", "Converted").default("Pending"),
		converted_by: Joi.string().max(10).optional(),
		company_id: Joi.number().integer().optional().default(1),
		assign_by: Joi.number().integer().optional(),
		last_assign_date: Joi.date().optional(),
		project_id: Joi.number().integer().optional(),
		salary: Joi.number().max(6).optional(),
	}),

	createUserSchema: Joi.object({
		name: Joi.string().max(191).required(),
		email: Joi.string().email().max(191).allow(null, "").optional(),
		password: Joi.string().min(6).max(191).required(),
		mobile: Joi.string().max(191).allow(null, "").optional(),
		gender: Joi.string().valid("male", "female", "others").allow(null).optional(),
		role: Joi.string()
			.valid(
				"owner",
				"unit_head",
				"sales_coordinator",
				"team_lead",
				"agent",
				"process_head"
			)
			.optional(),
		role_id: Joi.number().integer().min(1).max(255).optional(),
		manager_id: Joi.number().integer().allow(null).optional(),
		status: Joi.string().valid("active", "deactive").optional(),
		login: Joi.string().valid("enable", "disable").optional(),
		// mac_id: Joi.string().min(1).required(),
		// mac_login: Joi.string().valid("enable", "disable").optional(),
	}),

	updateUserSchema: Joi.object({
		name: Joi.string().max(191).optional(),
		email: Joi.string().email().max(191).allow(null, "").optional(),
		password: Joi.string().min(6).max(191).optional(),
		mobile: Joi.string().max(191).allow(null, "").optional(),
		gender: Joi.string().valid("male", "female", "others").allow(null).optional(),
		role: Joi.string()
			.valid(
				"owner",
				"unit_head",
				"sales_coordinator",
				"team_lead",
				"agent",
				"process_head"
			)
			.optional(),
		role_id: Joi.number().integer().min(1).max(255).optional(),
		manager_id: Joi.number().integer().allow(null).optional(),
		status: Joi.string().valid("active", "deactive").optional(),
		login: Joi.string().valid("enable", "disable").optional(),
		// mac_id: Joi.string().min(1).optional(),
		// mac_login: Joi.string().valid("enable", "disable").optional(),
	}).min(1),

	updateUserStatusSchema: Joi.object({
		status: Joi.string().valid("active", "deactive").required(),
	}),

	createProjectSchema: Joi.object({
		company_id: Joi.number().integer().positive().allow(null).optional(),
		project_name: Joi.string().max(255).required(),
		project_short_code: Joi.string().max(255).allow(null, "").optional(),
		project_summary: Joi.string().allow(null, "").optional(),
		project_admin: Joi.number().integer().positive().allow(null).optional(),
		start_date: Joi.date().required(),
		deadline: Joi.date().allow(null).optional(),
		notes: Joi.string().allow(null, "").optional(),
		category_id: Joi.number().integer().positive().allow(null).optional(),
		client_id: Joi.number().integer().positive().allow(null).optional(),
		team_id: Joi.number().integer().positive().allow(null).optional(),
		feedback: Joi.string().allow(null, "").optional(),
		manual_timelog: Joi.string().valid("enable", "disable").optional(),
		client_view_task: Joi.string().valid("enable", "disable").optional(),
		allow_client_notification: Joi.string().valid("enable", "disable").optional(),
		completion_percent: Joi.number().integer().min(0).max(100).required(),
		calculate_task_progress: Joi.string().valid("true", "false").optional(),
		project_budget: Joi.number().allow(null).optional(),
		currency_id: Joi.number().integer().positive().allow(null).optional(),
		hours_allocated: Joi.number().allow(null).optional(),
		status: Joi.string().max(255).optional(),
		hash: Joi.string().allow(null, "").optional(),
		public: Joi.alternatives()
			.try(Joi.boolean(), Joi.number().valid(0, 1))
			.required(),
		enable_miroboard: Joi.number().valid(0, 1).optional(),
		miro_board_id: Joi.string().allow(null, "").optional(),
		client_access: Joi.number().valid(0, 1).optional(),
	}),

	updateProjectSchema: Joi.object({
		company_id: Joi.number().integer().positive().allow(null).optional(),
		project_name: Joi.string().max(255).optional(),
		project_short_code: Joi.string().max(255).allow(null, "").optional(),
		project_summary: Joi.string().allow(null, "").optional(),
		project_admin: Joi.number().integer().positive().allow(null).optional(),
		start_date: Joi.date().optional(),
		deadline: Joi.date().allow(null).optional(),
		notes: Joi.string().allow(null, "").optional(),
		category_id: Joi.number().integer().positive().allow(null).optional(),
		client_id: Joi.number().integer().positive().allow(null).optional(),
		team_id: Joi.number().integer().positive().allow(null).optional(),
		feedback: Joi.string().allow(null, "").optional(),
		manual_timelog: Joi.string().valid("enable", "disable").optional(),
		client_view_task: Joi.string().valid("enable", "disable").optional(),
		allow_client_notification: Joi.string().valid("enable", "disable").optional(),
		completion_percent: Joi.number().integer().min(0).max(100).optional(),
		calculate_task_progress: Joi.string().valid("true", "false").optional(),
		project_budget: Joi.number().allow(null).optional(),
		currency_id: Joi.number().integer().positive().allow(null).optional(),
		hours_allocated: Joi.number().allow(null).optional(),
		status: Joi.string().max(255).optional(),
		hash: Joi.string().allow(null, "").optional(),
		public: Joi.alternatives()
			.try(Joi.boolean(), Joi.number().valid(0, 1))
			.optional(),
		enable_miroboard: Joi.number().valid(0, 1).optional(),
		miro_board_id: Joi.string().allow(null, "").optional(),
		client_access: Joi.number().valid(0, 1).optional(),
	}).min(1),

	createProductSchema: Joi.object({
		company_id: Joi.number().integer().positive().allow(null).optional(),
		name: Joi.string().max(255).required(),
		price: Joi.string().max(255).required(),
		taxes: Joi.string().max(255).allow(null, "").optional(),
		allow_purchase: Joi.number().valid(0, 1).optional(),
		downloadable: Joi.number().valid(0, 1).optional(),
		downloadable_file: Joi.string().allow(null, "").optional(),
		description: Joi.string().allow(null, "").optional(),
		category_id: Joi.number().integer().positive().allow(null).optional(),
		sub_category_id: Joi.number().integer().positive().allow(null).optional(),
		hsn_sac_code: Joi.string().max(255).allow(null, "").optional(),
		default_image: Joi.string().max(255).allow(null, "").optional(),
	}),

	updateProductSchema: Joi.object({
		company_id: Joi.number().integer().positive().allow(null).optional(),
		name: Joi.string().max(255).optional(),
		price: Joi.string().max(255).optional(),
		taxes: Joi.string().max(255).allow(null, "").optional(),
		allow_purchase: Joi.number().valid(0, 1).optional(),
		downloadable: Joi.number().valid(0, 1).optional(),
		downloadable_file: Joi.string().allow(null, "").optional(),
		description: Joi.string().allow(null, "").optional(),
		category_id: Joi.number().integer().positive().allow(null).optional(),
		sub_category_id: Joi.number().integer().positive().allow(null).optional(),
		hsn_sac_code: Joi.string().max(255).allow(null, "").optional(),
		default_image: Joi.string().max(255).allow(null, "").optional(),
	}).min(1),
};
